#!/bin/bash

# Install package
if [[ $1 == '--prod' ]]; 
    then
        printf '\n-->> Building Atom reportlib (production)\n\n'
        pip install .
    else
        printf '\n-->> Building Atom reportlib (development)\n\n'
        pip install -e .
fi

printf '\n-->> Generating documentation\n\n'

# Build doc
 pdoc --html --force reportlib